version: "3.8"

services:

  db:
    build: ./Database
    networks:
      - day-trading
    ports:
      - "27017:27017"
  
  pollingservice:
    build: ./PollingService
    depends_on:
      - db
    networks:
      - day-trading
    restart: always

  frontend:
    build: ./Frontend
    depends_on:
      - transactionserver
    networks:
      - day-trading
    ports:
      - "3000:3000"

  #Create replicas of transaction server replicated is default deploy mode
  transactionserver:
    build: ./TransactionServer
    depends_on:
      - db
      - redis
    networks:
      - day-trading
    deploy:
      replicas: 10

  redis:
    build: ./cache
    container_name: redis
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    networks:
      - day-trading
    ports:
      - "6379:6379"
    expose:
      - "6379"

  loadbalancer:
    build: ./LoadBalancer
    container_name: loadbalancer
    depends_on:
      - transactionserver
      - pollingservice
    ports:
      - "5100:5100"
    networks:
      - day-trading
    restart: always
  
  quoteserver:
    build: ./QuoteServer
    ports:
      - "4444:4444"
    networks:
      - day-trading
    restart: always

  # uncomment the following to run load testing
  # influxdb:
  #   image: influxdb:1.8
  #   container_name: influxdb
  #   expose:
  #     - "8086"
  #   ports:
  #     - "8086:8086"
  #   networks:
  #     - day-trading
  #   volumes:
  #     - influxdb-data:/var/lib/influxdb
  #   environment:
  #     - INFLUXDB_DB=myk6db
  #     - INFLUXDB_HTTP_AUTH_ENABLED=false

  # grafana:
  #   image: grafana/grafana
  #   container_name: grafana
  #   ports:
  #     - "3001:3000"
  #   networks:
  #     - day-trading
  #   volumes:
  #     - grafana-data:/var/lib/grafana
  #     - grafana-config:/etc/grafana
  #     - grafana-logs:/var/log/grafana
  #     - grafana-plugins:/var/lib/grafana/plugins

  # k6:
  #   image: loadimpact/k6
  #   container_name: k6
  #   networks:
  #     - day-trading
  #   depends_on:
  #     - influxdb
  #   command: >
  #     run /testing/k6_test.js
  #     -o influxdb=http://influxdb:8086/myk6db
  #   volumes:
  #     - ./testing:/testing

volumes:
  influxdb-data: {}
  grafana-data:
  grafana-config:
  grafana-logs:
  grafana-plugins:

networks:
  # Create a new Docker network.
  # Bridge by Default
  day-trading: