version: "3.8"

services:

  db:
    build: ./Database
    networks:
      - day-trading
  
  pollingservice:
    build: ./PollingService
    depends_on:
      - db
    networks:
      - day-trading

  transactionserver:
    build: ./TransactionServer
    depends_on:
      - db
      - redis
    networks:
      - day-trading
    deploy:
      replicas: 10

  redis:
    build: ./cache
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    ports:
      - "6379:6379"


  loadbalancer:
    build: ./LoadBalancer
    depends_on:
      - transactionserver
      - pollingservice
    ports:
      - "5100:5100"
    networks:
      - day-trading

networks:
  # Create a new Docker network.
  day-trading: